-- TB_INSTA_IMAGE
INSERT INTO TB_INSTA_IMAGE VALUES(SEQ_INSTA_IMAGE.NEXTVAL,'익명의 패션사진1','/resource/insta-image');
INSERT INTO TB_INSTA_IMAGE VALUES(SEQ_INSTA_IMAGE.NEXTVAL,'익명의 패션사진2','/resource/insta-image');
INSERT INTO TB_INSTA_IMAGE VALUES(SEQ_INSTA_IMAGE.NEXTVAL,'익명의 패션사진3','/resource/insta-image');
INSERT INTO TB_INSTA_IMAGE VALUES(SEQ_INSTA_IMAGE.NEXTVAL,'익명의 패션사진4','/resource/insta-image');
INSERT INTO TB_INSTA_IMAGE VALUES(SEQ_INSTA_IMAGE.NEXTVAL,'익명의 패션사진5','/resource/insta-image');

-- TB_INSTAGRAM
INSERT INTO TB_INSTAGRAM VALUES(SEQ_INSTAGRAM.NEXTVAL,'옷은 내가 제일 잘입어','#패션','INSTA01',NULL,3,2);
INSERT INTO TB_INSTAGRAM VALUES(SEQ_INSTAGRAM.NEXTVAL,'인생패션입니다.','#인생','INSTA02',NULL,1,3);
INSERT INTO TB_INSTAGRAM VALUES(SEQ_INSTAGRAM.NEXTVAL,'아~ 내 청춘이여','#청춘','INSTA03',NULL,2,4);
INSERT INTO TB_INSTAGRAM VALUES(SEQ_INSTAGRAM.NEXTVAL,'내 옷 이쁘죠?','#내가최고','INSTA04',NULL,2,5);
INSERT INTO TB_INSTAGRAM VALUES(SEQ_INSTAGRAM.NEXTVAL,'이쁜 연보라','#퍼플','INSTA05',NULL,4,1);

-- TB_ANSWER_INSTAGRAM
INSERT INTO TB_ANSWER_INSTAGRAM VALUES(SEQ_ANSWER_INSTAGRAM.NEXTVAL,'와.. 잘입었다..',SYSDATE,NULL,NULL,NULL,3,2);
INSERT INTO TB_ANSWER_INSTAGRAM VALUES(SEQ_ANSWER_INSTAGRAM.NEXTVAL,'저 옷을 저렇게 매치했다니..',SYSDATE,NULL,NULL,NULL,4,1);
INSERT INTO TB_ANSWER_INSTAGRAM VALUES(SEQ_ANSWER_INSTAGRAM.NEXTVAL,'구린데요',SYSDATE,NULL,NULL,NULL,1,4);
INSERT INTO TB_ANSWER_INSTAGRAM VALUES(SEQ_ANSWER_INSTAGRAM.NEXTVAL,'최고에요!!',SYSDATE,NULL,NULL,NULL,2,5);
INSERT INTO TB_ANSWER_INSTAGRAM VALUES(SEQ_ANSWER_INSTAGRAM.NEXTVAL,'한 수 배우고 갑니다.',SYSDATE,NULL,NULL,NULL,5,3);

-- TB_LIKE
INSERT INTO TB_LIKE VALUES(SEQ_LIKE.NEXTVAL,2,2);
INSERT INTO TB_LIKE VALUES(SEQ_LIKE.NEXTVAL,1,4);
INSERT INTO TB_LIKE VALUES(SEQ_LIKE.NEXTVAL,3,5);
INSERT INTO TB_LIKE VALUES(SEQ_LIKE.NEXTVAL,4,1);
INSERT INTO TB_LIKE VALUES(SEQ_LIKE.NEXTVAL,2,3);