-- COMMENT(TB_HEADER)
COMMENT ON COLUMN TB_HEADER.HEADER_NO IS '말머리번호';
COMMENT ON COLUMN TB_HEADER.CONTENT IS '말머리내용';

-- COMMENT(TB_INQUIRE)
COMMENT ON COLUMN TB_INQUIRE.QNA_NO IS '문의번호';
COMMENT ON COLUMN TB_INQUIRE.QNA_TITLE IS '문의제목';
COMMENT ON COLUMN TB_INQUIRE.QNA_CONTENT IS '문의내용';
COMMENT ON COLUMN TB_INQUIRE.QNA_DATE IS '문의날짜';
COMMENT ON COLUMN TB_INQUIRE.QNA_VIEW_COUNT IS '조회수';
COMMENT ON COLUMN TB_INQUIRE.ANS_CONTENT IS '답변내용';
COMMENT ON COLUMN TB_INQUIRE.ANS_DATE IS '답변날짜';
COMMENT ON COLUMN TB_INQUIRE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_INQUIRE.HEADER_NO IS '말머리번호';
COMMENT ON COLUMN TB_INQUIRE.MANAGER_NO IS '관리자번호';
COMMENT ON COLUMN TB_INQUIRE.MEM_NO IS '회원번호';

-- COMMENT(TB_NOTICE)
COMMENT ON COLUMN TB_NOTICE.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN TB_NOTICE.NOTICE_TITLE IS '공지사항제목';
COMMENT ON COLUMN TB_NOTICE.NOTICE_CONTENT IS '공지사항내용';
COMMENT ON COLUMN TB_NOTICE.NOTICE_FILE IS '첨부파일';
COMMENT ON COLUMN TB_NOTICE.NOTICE_DATE IS '작성일';
COMMENT ON COLUMN TB_NOTICE.MANAGER_NO IS '관리자번호';

-- COMMENT(TB_FOLLOW)
COMMENT ON COLUMN TB_FOLLOW.FOLLOW_NO IS '팔로잉식별번호';
COMMENT ON COLUMN TB_FOLLOW.FOLLOWING_ID IS '팔로잉회원번호';
COMMENT ON COLUMN TB_FOLLOW.FOLLOWER_ID IS '팔로워회원번호';

-- INSERT(TB_HEADER)
-- INSERT INTO TB_HEADER VALUES(SEQ_HEADER.NEXTVAL, '말머리내용');
INSERT INTO TB_HEADER
VALUES(SEQ_HEADER.NEXTVAL, '상품문의');
INSERT INTO TB_HEADER
VALUES(SEQ_HEADER.NEXTVAL, '주문문의');
INSERT INTO TB_HEADER
VALUES(SEQ_HEADER.NEXTVAL, '교환/환불문의');
INSERT INTO TB_HEADER
VALUES(SEQ_HEADER.NEXTVAL, '기타문의');

-- INSERT(TB_INQUIRE)
-- INSERT INTO TB_INQUIRE VALUES(SEQ_INQUIRE.NEXTVAL, '문의제목', '문의내용', SYSDATE, 조회수, '답변내용', SYSDATE, '삭제여부', 말머리번호, 관리자번호, 회원번호);
INSERT INTO TB_INQUIRE
VALUES(SEQ_INQUIRE.NEXTVAL, '언제와여', '주문한지 세시간 지났는데 언제와요', SYSDATE, 0, '15시 이전 주문 건은 당일 17시에 출고됩니다.', SYSDATE, DEFAULT, 2, 2, 1);
INSERT INTO TB_INQUIRE
VALUES(SEQ_INQUIRE.NEXTVAL, '상품관련 문의 드립니다.', '해당 상품 재입고 언제 되나요', SYSDATE, 0, '해당 상품에 대한 재입고 계획이 없습니다.', SYSDATE, 'Y', 1, 3, 2);
INSERT INTO TB_INQUIRE
VALUES(SEQ_INQUIRE.NEXTVAL, '교환해주세요!', '한 사이즈 큰 치수로 부탁드려요', '2022-12-21', 0, '매장으로 다시 보내주시면 교환해 드리겠습니다.', '2022-12-21', DEFAULT, 3, 2, 3);
INSERT INTO TB_INQUIRE
VALUES(SEQ_INQUIRE.NEXTVAL, '오프라인 매장 위치', '위치가 어디요', '2022-11-17', 0, '강남구 역삼동 예솔솔파크 77층 8호입니다.', '2022-11-17', 'Y', 4, 3, 4);
INSERT INTO TB_INQUIRE
VALUES(SEQ_INQUIRE.NEXTVAL, '주문 취소 요청합니다', '방금 결제 했는데 취소 부탁드려요', '2022-09-01', 0, '해당 상품 출고 전으로 주문 취소 되었습니다, 감사합니다.', '2022-09-01', DEFAULT, 2, 1, 5);

-- INSERT(TB_NOTICE)
-- INSERT INTO TB_NOTICE VALUES(SEQ_NOTICE.NEXTVAL, '공지사항제목', '공지사항내용', '첨부파일', SYSDATE, 관리자번호);
INSERT INTO TB_NOTICE
VALUES(SEQ_NOTICE.NEXTVAL, '설 연휴 배송 안내!', '설 연휴 관련 배송안내입니다.', 'https://egnmall.kr/thumb/6666cd76f96956469e7be39d750cc7d9/598_801_251eceadb434ff7ea6f2efc9e777.jpg' , SYSDATE, 3);
INSERT INTO TB_NOTICE
VALUES(SEQ_NOTICE.NEXTVAL, '크크루삥뽕마스 이벤트', '산타가 쳐들어온다.', 'http://image.dongascience.com/Photo/2018/12/b4812ae3bc4584a2d13937ee819bffa4.jpg' ,'2022-12-15', 4);
INSERT INTO TB_NOTICE
VALUES(SEQ_NOTICE.NEXTVAL, '스포츠웨어의 정석! <나이키> 입점 안내	', 'JUST DO IT, NIKE.', 'http://www.apparelnews.co.kr/upfiles/manage/202006/7c90c12cd49cf8145c53457e06ed64a2.jpg' ,'2022-11-01', 1);
INSERT INTO TB_NOTICE
VALUES(SEQ_NOTICE.NEXTVAL, '추석 연휴 배송 안내', '송편도 꼭꼭 공지사항도 꼭꼭.', 'https://health.chosun.com/site/data/img_dir/2020/09/29/2020092901408_0.jpg' ,'2022-09-20', 2);
INSERT INTO TB_NOTICE
VALUES(SEQ_NOTICE.NEXTVAL, '오잉? 여름이다! 여름 휴가 맞이 이벤트', '내일뭐입지 팀이 휴가를 갑니다', 'http://magazine.hankyung.com/magazinedata/images/raw/201807/9181b8418f633ec1f9f81f70bcdbc8d8.jpg' ,'2022-08-18', 5);

-- INSERT(TB_FOLLOW)
INSERT INTO TB_FOLLOW
VALUES(SEQ_FOLLOW.NEXTVAL, 1,2);
INSERT INTO TB_FOLLOW
VALUES(SEQ_FOLLOW.NEXTVAL, 1,3);
INSERT INTO TB_FOLLOW
VALUES(SEQ_FOLLOW.NEXTVAL, 1,4);
INSERT INTO TB_FOLLOW
VALUES(SEQ_FOLLOW.NEXTVAL, 2,3);
INSERT INTO TB_FOLLOW
VALUES(SEQ_FOLLOW.NEXTVAL, 2,4);