INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '아우터');
INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '상의');
INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '하의');
INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '슈즈');

INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin01', 'pwd01');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin02', 'pwd02');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin03', 'pwd03');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin04', 'pwd04');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin05', 'pwd05');

INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '나이키');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '무아무아');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '아디다스');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '키르시');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, 'OiOi');

INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'S', 1);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'M', 2);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'L', 3);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'XL', 4);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'FREE', 5);