-- COMMENT TB_CATEGORY
COMMENT ON COLUMN TB_CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN TB_CATEGORY.CATEGORY_NAME IS '카테고리이름';

-- COMMENT TB_MANAGER
COMMENT ON COLUMN TB_MANAGER.MANAGER_NO IS '관리자번호';
COMMENT ON COLUMN TB_MANAGER.MANAGER_ID IS '관리자아이디';
COMMENT ON COLUMN TB_MANAGER.MANAGER_PWD IS '관리자비밀번호';

-- COMMENT TB_BRAND
COMMENT ON COLUMN TB_BRAND.BRAND_NO IS '브랜드번호';
COMMENT ON COLUMN TB_BRAND.BRAND_NAME IS '브랜드이름';

-- COMMENT TB_OPTION
COMMENT ON COLUMN TB_OPTION.OPTION_NO IS '옵션번호';
COMMENT ON COLUMN TB_OPTION.OPTION_SIZE IS '상품사이즈';
COMMENT ON COLUMN TB_OPTION.PRODUCT_NO IS '상품번호';

-- INSERT TB_CATEGORY
INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '아우터');
INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '상의');
INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '하의');
INSERT INTO TB_CATEGORY VALUES(SEQ_CATEGORY.NEXTVAL, '슈즈');

-- INSERT TB_MANAGER
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin01', 'pwd01');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin02', 'pwd02');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin03', 'pwd03');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin04', 'pwd04');
INSERT INTO TB_MANAGER VALUES(SEQ_MANAGER.NEXTVAL, 'admin05', 'pwd05');

-- INSERT TB_BRAND
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '나이키');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '무아무아');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '아디다스');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, '키르시');
INSERT INTO TB_BRAND VALUES(SEQ_BRAND.NEXTVAL, 'OiOi');

-- INSERT TB_OPTION
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'S', 1);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'M', 2);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'L', 3);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'XL', 4);
INSERT INTO TB_OPTION VALUES(SEQ_OPTION.NEXTVAL, 'FREE', 5);