INSERT INTO TB_PRODUCT_IMAGE VALUES(SEQ_PRODUCT_IMAGE,'멋진 운동화 사진','/resources/img1.jpg',1);
INSERT INTO TB_PRODUCT_IMAGE VALUES(SEQ_PRODUCT_IMAGE,'멋진 숏자켓 사진','/resources/img2.jpg',2);
INSERT INTO TB_PRODUCT_IMAGE VALUES(SEQ_PRODUCT_IMAGE,'멋진 후드티 사진','/resources/img3.jpg',3);
INSERT INTO TB_PRODUCT_IMAGE VALUES(SEQ_PRODUCT_IMAGE,'멋진 조거팬츠 사진','/resources/img4.jpg',4);
INSERT INTO TB_PRODUCT_IMAGE VALUES(SEQ_PRODUCT_IMAGE,'멋진 티셔츠 사진','/resources/img5.jpg',5);

INSERT INTO TB_PRODUCT VALUES(SEQ_PRODUCT.NEXTVAL,'운동화','멋진 재질을 가진 운동화입니다.',33000,5,'2023-02-03',20,NULL,1,2);
INSERT INTO TB_PRODUCT VALUES(SEQ_PRODUCT.NEXTVAL,'체리퍼 숏자켓','멋진 재질을 가진 숏자켓입니다.',120000,4,'2023-01-03',40,NULL,3,1);
INSERT INTO TB_PRODUCT VALUES(SEQ_PRODUCT.NEXTVAL,'후드티','멋진 재질을 가진 후드티입니다.',52000,2,'2023-01-30',30,NULL,2,3);
INSERT INTO TB_PRODUCT VALUES(SEQ_PRODUCT.NEXTVAL,'조거팬츠','멋진 재질을 가진 바지입니다.',33000,12,'2023-02-02',100,NULL,4,5);
INSERT INTO TB_PRODUCT VALUES(SEQ_PRODUCT.NEXTVAL,'티셔츠','멋진 재질을 가진 티셔츠입니다.',27000,8,'2023-01-25',150,NULL,3,4);

INSERT INTO TB_CART VALUES(SEQ_CART.NEXTVAL,6,2,1);
INSERT INTO TB_CART VALUES(SEQ_CART.NEXTVAL,8,3,2);
INSERT INTO TB_CART VALUES(SEQ_CART.NEXTVAL,1,1,3);
INSERT INTO TB_CART VALUES(SEQ_CART.NEXTVAL,3,5,4);
INSERT INTO TB_CART VALUES(SEQ_CART.NEXTVAL,7,4,5); 

COMMENT ON COLUMN TB_PRODUCT_IMAGE.PRODUCT_IMG_NO IS '이미지번호';
COMMENT ON COLUMN TB_PRODUCT_IMAGE.PRODUCT_IMG_NAME IS '이미지이름';
COMMENT ON COLUMN TB_PRODUCT_IMAGE.PRODUCT_IMG_SRC IS '이미지경로';
COMMENT ON COLUMN TB_PRODUCT_IMAGE.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN TB_PRODUCT.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_NAME IS '상품이름';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_DESC IS '상품설명';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_PRICE IS '가격';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_STOCK IS '재고';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_ENROLL_DATE IS '등록날짜';
COMMENT ON COLUMN TB_PRODUCT.PRODUCT_VIEW_COUNT IS '조회수';
COMMENT ON COLUMN TB_PRODUCT.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_PRODUCT.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN TB_PRODUCT.BRAND_NO IS '브랜드번호';

COMMENT ON COLUMN TB_CART.CART_NO IS '장바구니번호';
COMMENT ON COLUMN TB_CART.CART_QNT IS '수량';
COMMENT ON COLUMN TB_CART.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN TB_CART.MEM_NO IS '회원번호';




